development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: eventcasts_development
  pool: 5
  username: root
  password:
  socket:  <%=
        ['/var/run/mysqld/mysqld.sock',           # ubuntu/debian
         '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: eventcasts_test
  pool: 5
  username: root
  password:
  socket:  <%=
        ['/var/run/mysqld/mysqld.sock',           # ubuntu/debian
         '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: eventcasts_production
  pool: 5
  username: root
  password: 8dJtAQ9o
  socket:  <%=
        ['/var/run/mysqld/mysqld.sock',           # ubuntu/debian
         '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>